Numoy array is open source liberary in python used for numerical computing. a special data structure called n dimensional array 

In [1]:
import numpy as np
my_list= [1,2,3,4,5]
my_array = np.array(my_list)

In [2]:
print(my_array)

[1 2 3 4 5]


In [3]:
print (type(my_array))

<class 'numpy.ndarray'>


In [5]:
my_array.shape

(5,)

In [6]:
mylist1 = [1,2,3,4,5]
mylist2 = [6,7,8,9,10]
mylist3 = [11,12,13,14,15]
my_2d_array = np.array([mylist1, mylist2, mylist3])
print (my_2d_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
my_2d_array.shape

(3, 5)

In [10]:
my_2d_array.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [16]:
print(my_2d_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [21]:
my_2d_array[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [17]:
my_2d_array[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [28]:
my_2d_array = np.arange(1,13,step=3)
my_2d_array

array([ 1,  4,  7, 10])

In [34]:
my_2d_array= np.linspace(0,10, num=50)
my_2d_array

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])